### ISSUE TITLE
Unknown licenses

### ISSUE THREAD

**Issue by shlyakpavel** [octave-app/octave-app#15]
## Description

I downloaded 4.4.1 - beta2 dmg, opened VERSIONS file
<img width="752" alt="image" src="https://user-images.githubusercontent.com/19782228/50741525-a1d2b800-1217-11e9-9abc-303326c39ca4.png">
Licenses for 3rd party components seem to be missing

**Comment by apjanke** [comment]
Uh oh. That's no good. I'll get it sorted out.

**Comment by apjanke** [comment]
Okay, two things are going wrong:

* Some of the indirect dependencies are missing their license info in [`homebrew-octave-app/assets/COPYING/licenses.csv`](https://github.com/octave-app/homebrew-octave-app/blob/55bd1a1bf0adb61fb70e935355f4c5404abf5f88/assets/COPYING/licenses.csv)
* The formulae include a version in their name, but the license are listed against the base package name, so all the lookups are failing anyway.

**Comment by apjanke** [comment]
Fixed in https://github.com/octave-app/homebrew-octave-app/commit/4efaa98c1ac844a2b8cf011a3be712f2913f2295 and https://github.com/octave-app/homebrew-octave-app/commit/1acf34fb497ad50d121fb1ac1aeb315817f1116c.

I've posted a new 4.4.1-beta3 prerelease that includes this fix: https://github.com/octave-app/octave-app/releases/tag/v4.4.1-beta3

Thanks for pointing this out!
