### ISSUE TITLE
octave 4.4.1 dyld crash

### ISSUE THREAD

**Issue by Izbear125** [octave-app/octave-app#198]
Have been successfully running octave 3.4.0 on mac OS X 10.11.
Upgraded to octave-4.4.1 and successfully ran simple computations without
graphics.  Tried simple plot(x,y)-- terminated with error message

octave:3> plot(x,y);
dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/fontconfig/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/fontconfig/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
fatal: caught signal Trace/BPT trap: 5 -- stopping myself...
fatal: caught signal Segmentation fault: 11 -- stopping myself...
Segmentation fault

**Comment by apjanke** [comment]
Hi @Izbear125!

I'm afraid Octave.app does not support OS X 10.11. We build Octave.app on macOS 10.12 or 10.13, so only 10.13 and later are supported. This is because a) Octave.app is built on top of Homebrew, and Homebrew only supports the most recent 3 versions of macOS, and b) I can't get VMs with earlier versions of macOS to work reliably in my setup.

You may have some luck installing Octave using our custom Homebrew formulae. To do this:
1. Install Homebrew
2. Install MacTeX if you want the documentation to work
3. In a shell, run:
```bash
brew tap octave-app/octave-app
brew install octave-octave-app@4.4.1
```

That might get you a build of Octave 4.4.1 with a working GUI. No guarantees, though, since Homebrew does not support OS X 10.11 any more.

You may also have luck installing Octave 4.4.1 using MacPorts, which supports older versions of OS X than Homebrew does. They still have a 4.4.1 Octave port supported by core MacPorts.

**Comment by Izbear125** [comment]
Octave-4.4.0 apparently runs successfully with graphics for Mac OS x10.11.6

**Comment by apjanke** [comment]
Excellent!
