### ISSUE TITLE
Native build for Apple Silicon (arm64)

### ISSUE THREAD

**Issue by mpiqueca** [octave-app/octave-app#205]
Not a bug; a discussion I wanted to kick off.
Clearly, building Octave for Apple Silicon will take some work. Neither ‘macports’ nor ‘brew’ offer much so far. Anyone interested in following up with building Apple Silicon Octave from source (which I know seems to need tools not yet publicly available) maybe post on the Apple Developer Forum? - Michael Pique

**Comment by apjanke** [comment]
Personally, I'm happy to just wait until upstream Octave, OpenBLAS, and Homebrew or MacPorts tackle this problem. There's not much Octave.app can do as a packager until all those have Apple Silicon support. And I'm not eager to be an early adopter here.

**Comment by Physalis87** [comment]
Just a small question to bump this up: Will ocatave-app 6.2.0 beta support Macs arm64?

**Comment by apjanke** [comment]
It should run on an M1, but it will be running under the Rosetta emulator (or whatever they're calling it this time); it's not a native ARM build.

**Comment by neurolabusc** [comment]
Any update on this? When I install the command line octave with brew, I get version 6.4.0 with native arm64 support. Complicated programs like SPM12 seem to compile mex files appropriately and run functions, though obviously no GUI. It would be great if `octave.app` could bring all the great GUI goodness to the mix. Regardless, thanks for all the terrific work.

```
$ octave
GNU Octave, version 6.4.0
...
octave:1> uname
ans =

  scalar structure containing the fields:

    sysname = Darwin
    nodename = Chriss-MacBook-Air.local
    release = 20.6.0
    version = Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
    machine = arm64
```

**Comment by apjanke** [comment]
Hi @neurolabusc !

Soooooo... we got that MacStadium M1 Mac, so we have a native ARM/Apple Silicon build box now.

Buuuut, the Octave.app build is currently broken and I don't know why. (See https://github.com/octave-app/octave-app/issues/229#issuecomment-951530565). And we have an issue with Homebrew: macOS 10.14 Mojave has fallen out of support under Homebrew. I'd like to keep Octave.app supporting 10.14, for users who are still on it (like myself 😉): 10.15 broke a lot of applications, so some users are sticking on 10.14.

But maybe that's not an issue for the ARM build: macOS 11 Big Sur is the oldest version of macOS that supports the M1 chips, so "supporting macOS 10.14 on ARM" doesn't make sense. We'll need to split the build and do separate releases of x65 and arm64 Octave.app anyway – Homebrew doesn't support "universal" builds that will work on both, and that installation would probably be huge; Octave.app is big enough already. So I can try to roll an ARM build of Octave.app on macOS 11 and see how that goes; we could release that on its own even if the x64/macOS 10.14 build is broken.

I'll give this a try tonight if I don't have to hit the hay too soon after work.

**Comment by apjanke** [comment]
Here's a checklist of what I think we'll need to do now that Homebrew has good ARM support.

Will need:

* [ ] Rearrange the website's downloads page to have two architecture-specific downloads.
* [ ] Modify the bundler to put an architecture suffix on the filename of at least the M1 DMG file, so the x64 and M1 installer files have different names and can both be uploaded into a single scope, such as the set of files on a GitHub release.
* [ ] Anything else???

**Comment by Danby108** [comment]
Just a word of appreciation: Thanks for working on a native build for Apple Silicon!!

**Comment by apjanke** [comment]
You're welcome! Sorry this is taking so long.

I have an M1 Max MacBook Pro now, so I can do fast local builds instead of just using the MacStadium machine; hopefully that'll make this easier.

**Comment by apjanke** [comment]
Note for future reference: we could make a Universal build of Octave.app that works on both x64 and Apple Silicon, and would make the installation process simpler for users, but I don't think that's a good idea: Octave.app is already a huge install, and a Universal build would probably inflate that by a lot.

**Comment by Danby108** [comment]
I agree, I think most users would prefer downloading a smaller app tailored for their specific machines. i certainly would!

Which reminds me of the last time Apple switched architectures, from PowerPC to Intel. They had the same approach of encouraging every developer to distribute "universal" apps that would work on either platform. Trouble was, as you've pointed out, this results in much bigger installs, maybe twice the size they would otherwise be. If you've got a lot of big apps, this can add up to a LOT of wasted disk space.

Does anyone know of an app that can trim off the portions of the apps that aren't needed, to reclaim that disk space? I remember someone came up with one during the last architecture switch. If no one's done that yet, I think it would be a good idea, and perhaps a lucrative one for them!

**Comment by apjanke** [comment]
> Does anyone know of an app that can trim off the portions of the apps that aren't needed, to reclaim that disk space?

This is maybe feasible, since the per-architecture code chunks are discrete and readily identifiable inside the binaries. But I think this would be incompatible with code signing, because the app bundle is signed in its original state. And I'd like to (some day) [implement code signing for Octave.app](https://github.com/octave-app/octave-app/issues/83).

Plus, self-modifying executables just give me the heebie jeebies.

So even if this exists, I don't think I'd support it in Octave.app directly; this is something that advanced users would need to apply on a per-install basis to a Universal build. And I think that providing a Universal build of Octave.app in addition to x64 and Apple Silicon builds might be confusing and would definitely be inconvenient for me in the build process, I think I'd rather not do that.

**Comment by Aleishus** [comment]
Is arm64 available?

**Comment by apjanke** [comment]
> Is arm64 available?

Not yet, I'm afraid. Currently working on getting the build to run at all, between my own bugs and Homebrew dropping support for older macOSes.

Once I get that sorted, then yes, I'll make an arm64/AppleSilicon build for the next Octave.app release.

**Comment by apjanke** [comment]
The native Apple Silicon build seems to be working now. (Using code on the `lets-build-2023` branch in the octave-app-bundler repo and recently updated formulae in our homebrew-octave-app tap.) I've got an AS version building and running locally for 8.4.0. Currently blocked on some problem with the GitHub Releases downloads of the DMG file; see https://github.com/octave-app/octave-app/issues/244.

**Comment by apjanke** [comment]
Think we have a workaround for the DMG issue: run `xattr -c ~/Downloads/Octave-*.dmg` on the downloaded DMG file before you open it and drag the app to `/Applications`.

That means I think we've got a native Apple Silicon build of Octave 8.x (prerelease) ready for testing. You can find it on this 8.4.0 alpha1 release page. The DMG file that doesn't have "Intel" in its file name is a native Apple Silicon build. Requires macOS 12 or newer.

https://github.com/octave-app/octave-app/releases/tag/v8.4.0_alpha1

**Comment by apjanke** [comment]
Apple Silicon builds for Octave.app are working regularly now (with changes on the branches). Haven't had any AS-specific issues for a while.

The "app is damaged" issue looks specific to the DMG creation and newer versions of macOS, not about the AS-architecture build of the app itself. Going to handle that under ticket [#244 "App "damaged" for GitHub Release DMG downloads"](https://github.com/octave-app/octave-app/issues/244).

Calling this issue closed. The upcoming Octave.app 8.4.0 release will include a native Apple Silicon build.
