### ISSUE TITLE
Can't install control pkg: "invalid version number in '-mmacosx-version-min=11.4'"

### ISSUE THREAD

**Issue by algonuevo** [octave-app/octave-app#238]
## Description

After "pkg install -forge control", this is what happened:

```
tar: Failed to set default locale
clang: error: invalid version number in '-mmacosx-version-min=11.4'
clang: error: invalid version number in '-mmacosx-version-min=11.4'
make: *** [slicotlibrary.a] Error 1
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin/mkoctfile-6.2.0 -Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
if [ "0" = "1" ]; then \
                echo "copy routines using DGGES"; \
                cp SB04OD.fortran ./sltmp/SB04OD.f; \
                cp SG03AD.fortran ./sltmp/SG03AD.f; \
                cp SG03BD.fortran ./sltmp/SG03BD.f; \
        fi;
cp AB08NX.fortran ./sltmp/AB08NX.f
cp AG08BY.fortran ./sltmp/AG08BY.f
cp SB01BY.fortran ./sltmp/SB01BY.f
cp SB01FY.fortran ./sltmp/SB01FY.f
cp SB06ND.fortran ./sltmp/SB06ND.f
cp TB01MD.fortran ./sltmp/TB01MD.f
cp TB01ND.fortran ./sltmp/TB01ND.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cp TG04BX.fortran ./sltmp/TG04BX.f
cp ODLTZM.fortran ./sltmp/ODLTZM.f
cp makefile.slicot ./sltmp/makefile
cd sltmp; /Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin/mkoctfile-6.2.0 -w -c MA02ID.f; rm MA02ID.f; /Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin/mkoctfile-6.2.0 -c *.f;

error: pkg: error running 'make' for the control package.
error: called from
    configure_make at line 110 column 9
    install at line 196 column 7
    pkg at line 568 column 9
```

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
SHELL=/bin/zsh
TERM=xterm
TMPDIR=/var/folders/1t/d0mw894d3msb_cqxfyfq0nkw0000gn/T/
LC_NUMERIC=C
USER=d-macbook
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vbjzeH3SGJ/Listeners
__CF_USER_TEXT_ENCODING=
<img width="1194" alt="octave error" src="https://user-images.githubusercontent.com/108028077/175124567-d0069290-9f9e-4267-a481-62854e7c91ad.png">
<img width="1194" alt="octave error" src="https://user-images.githubusercontent.com/108028077/175124617-693816f6-6817-422b-a02f-01dcc2051e78.png">
0x1F5:0x0:0x0
COLUMNS=116
PATH=/Applications/Octave-6.2.0.app/Contents/Resources/usr/bin/:/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/gnuplot-octave-app/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/api-v55/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin
_=/usr/bin/env
__CFBundleIdentifier=org.octave-app.Octave
PWD=/Users/d-macbook
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.53.3/iccprofiles/ -sGenericResourceDir=/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.53.3/Resource/ -sFontResourceDir=/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.53.3/Resource/Font
LANG=en_PR.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-6.2.0.app/Contents/Resources/usr/bin/gfortran
LINES=50
XPC_SERVICE_NAME=0
HOME=/Users/d-macbook
SHLVL=2
FC=/Applications/Octave-6.2.0.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=d-macbook
DISPLAY=/private/tmp/com.apple.launchd.ZdOehZH70G/org.macosforge.xquartz:0
LC_TIME=C
ans = 0
```

**Comment by algonuevo** [comment]
@apjanke can you help me?

**Comment by apjanke** [comment]
> clang: error: invalid version number in '-mmacosx-version-min=11.4'
> clang: error: invalid version number in '-mmacosx-version-min=11.4'

Well, that's a new one! Looks like an incompatibility between the build options that `pkg` is using and your system `clang` compiler, or the Mac SDKs available in your Xcode installation.

What versions of macOS and Xcode are you running here?

I'm gonna call this problem a "weird" one. Could you run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

**Comment by rgftech** [comment]
Hello, I have the same issue. Was there any solution to install the pkg control and the signal?

**Comment by apjanke** [comment]
Hi, @rgftech!

I'm afraid I was never able to reproduce this problem, so I don't know what caused it or how to fix it. `pkg install -forge control` is working for me in Octave.app 8.4.0 and 9.2.0 beta1 on my Macs running recent macOS versions.

Could you tell me more about the Mac you're running on, like which versions of macOS and Xcode you have? And try running `octave_app_diagnostic_dump` in Octave.app (or `octapp.diagnostic_dump` in the 9.1 or 9.2 releases) and post the output here?

## Discussion on Octave Discourse

This issue was recently also reported in [post 5724 on the Octave Discourse](https://octave.discourse.group/t/cant-install-pkg-such-as-control-or-signal-when-using-forge-error-make-message-in-prompt-command-macos-octave-6-2-9-2/5724).

**Comment by apjanke** [comment]
I can now reproduce this problem, or at last very similar ones that produce an "invalid version number in '-mmacosx-version-min=11.5'" error. It happens when I run an Octave.app on a macOS + Xcode that is significantly older than the versions that the Octave.app was built with. I think the `mkoctfile` and `mex` functions, and their related compiler-option things, in the Octave.app include that '-mmacosx-version-min=11.5' in their compiler options. And when you run that on a Mac with an older version of Xcode, that Xcode and its `clang` don't know about that newer macOS version like "11.4" or "11.5", and you get this error.

Not a whole lot for Octave.app to do here, I think. I think the fix is to use a version of macOS and Xcode that is supported by that version of Octave.app. Octave.app typically supports the most recent 3, or sometimes 4, major versions of macOS, as of the time that Octave.app was built.

Try updating your Xcode and Xcode CLT if you haven't done so recently; that might get this working without a macOS upgrade.

If this is happening to you on macOS and Xcode versions that are supported by Octave.app, please re-open this issue, and let me know which versions of macOS and Xcode you are running, and attach the output of `octapp.diagnostic_dump`.

## Octave.app supported minimum macOS versions

* 6.2.0 - macOS 11
* 8.4.0 - currently macOS 14, but an 8.4.0 update 1 will come out soon that supports macOS 12
* 9.1.0 (upcoming) - macOS 12
