### ISSUE TITLE
octave-gui quit unexpectedly

### ISSUE THREAD

**Issue by mleiva02** [octave-app/octave-app#240]
After installing octave on my mac, i tried to run the app but it crashed. I tried to reopen, restart the computer and nothing works.

<img width="1003" alt="Screen Shot 2022-07-28 at 09 20 02" src="https://user-images.githubusercontent.com/110185361/181575281-fd639313-8fba-4f3a-8a6f-8ed493c6ca13.png">

**Comment by apjanke** [comment]
Well, that sucks!

Let's try to figure this one out.

Normally, Octave.app doesn't crash that much[1], so I'm going to classify this issue as "weird". Do you see this part in the Octave.app issue template, where it asks you to run `system env` and `octave_app_diagnostic_dump` and then include their output in the bug report? (Screenshot of GitHub Issues page below.) Please do that here.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/2618447/183055656-a3290445-3aff-4852-9acf-12109fc71f59.png">

[1] Honestly, I'm totally guessing here; I have no actual statistics or crash diagnostic data on our userbase. I'm just saying this because we don't get that many flat-out crash reports here on the GitHub issue tracker or the main Octave Discourse, and I hope that means that Octave.app doesn't crash that much, as opposed to it crashes all the time and then our potential users just give up on us and never contact us again. But who knows, really?

**Comment by kaylai** [comment]
I'm having the same problem. I would provide output from system env, but I can't even open Octave.app. When I double click the app file, I get the "Welcome!" wizard (pictured below) and go through the steps. Upon clicking "Finish" in the third and final box, the app immediately crashes.

I'm running MacOS 12.5.1

![Screen Shot 2022-09-12 at 1 13 43 PM](https://user-images.githubusercontent.com/6538370/189726534-50d4e303-f38e-4424-8b7d-7425cb4a222a.png)
![Screen Shot 2022-09-12 at 1 14 15 PM](https://user-images.githubusercontent.com/6538370/189726547-f81a1568-df4c-4c6b-b6e0-64e6f400718c.png)

**Comment by apjanke** [comment]
Well you're in luck! I got a new MacBook Pro a couple months ago, so now I can actually run the newer macOS and try to diagnose this.

What model MacBook are you on? Is it Intel or Apple Silicon?

My bet here is that Octave.app is so far behind in getting new Octave builds out, it would probably be best to try to get a build of Octave.app 7.1 or 7.2 working, with up-to-date libs and dependencies, than try to diagnose the problem with older Octaves on newer macOSes as a first resort. Hopefully I'll have some free time soon to do that.

**Comment by kaylai** [comment]
Oh nice! I'm on a 2019 MacBook Pro 16-inch (Intel).

I installed Octave 7.2.0 via brew, and that is working (`sudo octave --gui`), but only when I run it with sudo.

**Comment by apjanke** [comment]
Hi y'all. I've got a mostly-working prerelease of Octave.app 8.4.0 up, built against macOS 14, which may address this problem, or at least give us a more-recent baseline to work from.

https://github.com/octave-app/octave-app/releases/tag/v8.4.0_alpha1

Please note there's a special installation step of using `xattr` to un-quarantine the DMG before doing the install that you really need to do now.

Lemme know if you get a chance to test this build, and whether it works?
