### ISSUE TITLE
Who's using Octave.app?

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#25]
I'm curious about who's using Octave.app and how many users we have.

Let's treat this issue as a survey. If you're using Octave.app, feel free to leave a comment here introducing yourself and letting us know what you use Octave.app for. If you're using Octave.app at an university or other institution or business, it would be interesting to know that, too!

**Comment by mpiqueca** [comment]
Our group, which includes people from Scripps Research, UC San Diego, and the San Diego Supercomputer Center, is using Octave.app as the foundation for an interactive graphics application to allow scientists to interpret biologically relevant mass spectrometry experiments on protein and DNA samples. Specially, we are building novel computational and visual tools for hydrogen-deuterium exchange experiments that allow mapping of a protein surface to detect changes upon binding of DNA, small drug-like molecules, or other proteins.  We are using almost entirely Macs, and chose Octave.app over Homebrew and MacPorts for simplicity. It is also important that Octave.app includes the new GUI file-chooser and tables, whereas Homebrew, in our hands at least, does not.

Michael Pique
The Scripps Research Institute, La Jolla, California, USA

**Comment by apjanke** [comment]
@mpiqueca That's awesome! Thanks for letting us know about you. I didn't know we were being used for such serious applications.

> It is also important that Octave.app includes the new GUI file-chooser and tables, whereas Homebrew, in our hands at least, does not.

I'm not familiar with either of these things. Could you point me at some doco for them so I can get informed and make sure we're handling them right?

**Comment by jrminter** [comment]
I am using the current developer build on MacOS. In general it works quite well. I have some issues with Octave Forge packages not building. I use homebrew for a package manager. This is one of the cases where the Windows version is easier - the current 5.1.0 release comes with many of the OctaveForge packages. It runs OK in a Win10x64 Parallels virtual machine.

I haven't found a good place on the internet to find tips on building packages from OctaveForge on macos Mojave. Any suggestions would be appreciated...

**Comment by rdzman** [comment]
I am a researcher at Cornell University and the lead developer of [MATPOWER](https://github.com/MATPOWER/matpower), a set of Matlab-language tools for power grid simulation and optimization, used worldwide in research, education and industry. Since I work on macOS, I find Octave.app the simplest way to install multiple versions of Octave for testing MATPOWER.

I also use Octave for some of my own MATPOWER related consulting work.

**Comment by apjanke** [comment]
Neat! I did a bit of power and nat gas modeling stuff in Matlab when I was working on some hedge fund Energy desks a few years back. I didn't know about the MATPOWER library. I've added it to the list of FLOSS Matlab libraries I curate at https://github.com/apjanke/SomeMatlabFlossProjects.

**Comment by apjanke** [comment]
@jrminter:

> This is one of the cases where the Windows version is easier - the current 5.1.0 release comes with many of the OctaveForge packages

So, as a user, would you prefer that Octave.app came with a lot of the common Octave Forge packages, even if they weren't the latest versions? We're considering that: https://github.com/octave-app/octave-app-bundler/issues/60; feel free to leave feedback there.

> I haven't found a good place on the internet to find tips on building packages from OctaveForge on macos Mojave. Any suggestions would be appreciated...

I haven't seen anything like that. But if you're having trouble installing packages under Octave.app, you can post them as issues on this repo, and we'll help you sort it out, either fixing Octave.app or helping you report the issue upstream to the Octave Forge package maintainers and working with them to get the package fixed for Mac. Separate issue for each package that isn't installing, please.

**Comment by suednimh** [comment]
I am research support at the USDA-Forest Products Laboratory. One of our scientists does 2D NMR of wood. One of his current projects is analyzing the changes in chemical makeup that occur during tree growth, and trying to quantify the types of chemical linkages in lignin, cellulose and hemicellulose, to provide information for biorefinery processing of wood. (In order to move from petroleum based chemicals and materials, we need to develop the bio based analogues that can be produced from renewable plant based resources. Trees are the model, and the knowledge from trees can be used to process forest thinnings/brush/grasses/wood-based demolition waste.)  

The current workflow uses Matlab to process the binary exports from the NMR software, SIMCA for PCA (principal component analysis), and reprocess in Matlab.  Funding is always an issue for us, and widely disseminating the results of research in an open-source tool means more people will be able replicate the research and build on it.  My goal is to be able to switch the workflow over to Octave (to replace MatLab) and R (to replace SIMCA) using the ropls package.

**Comment by apjanke** [comment]
Hi folks. Thanks for responding and letting us know how you're using Octave.app!

I'd really like to get some broader insight in to who our users are, what versions of macOS and Octave.app they're running, and what they want and need out of Octave.app. This will guide our decisions for future Octave.app development.

Since you're the few folks who found this GitHub issue and responded, I thought I'd ask you: Do you have any ideas on how we can do outreach to the broader Octave.app user community? Should we set up a mailing list, a forum, include a feedback form in the Octave.app GUI itself, ...?

I set up another issue for talking about how to do this: https://github.com/octave-app/octave-app/issues/209. Your feedback is welcome!

**Comment by apjanke** [comment]
I'm closing this ticket so it doesn't show up as a "TODO" item in our main issue list.

Feel free to still drop comments here if you are an Octave.app user and want to introduce yourself and tell us about your use cases!
