### ISSUE TITLE
Adding Apple accelerate BLAS for Apple silicon

### ISSUE THREAD

**Issue by tangjinchuan** [octave-app/octave-app#281]
Dear apjanke,
Matlab has switched from OpenBLAS to Accelerate to achieve many speed-ups (3.7x faster Matrix-Matrix multiplication, 2x faster LU factorisation, 1.7x faster Cholesky Decomp.). Could you please consider bringing Apple Accelerate back to octave-app?
https://blogs.mathworks.com/matlab/2023/12/13/life-in-the-fast-lane-making-matlab-even-faster-on-apple-silicon-with-apple-accelerate/

Thank you very much!
Best wishes,
Jinchuan

**Comment by apjanke** [comment]
This is probably more a question for the "upstream" core Octave developers, and not Octave.app per se. Octave has never had much support for Apple Accelerate - AFAICT, almost none of the core Octave developers used Accelerate much, and some of the core test suite failed under Accelerate. (Maybe spurious failures related to floating-point being an approximate type, or maybe legit failures; I could never figure it out.) Octave.app is mostly about _packaging_ Octave into a native Mac app bundle and installer, for user convenience, but not changing its behavior much otherwise. If core Octave doesn't have first-class support for Accelerate – both in terms of build & execution tools, and in terms of what the core Octave team can help support when users have questions or problems – I don't think that's a good fit for including in Octave.app. Octave.app targets entry-level Octave users, and its goal is to maximize simplicity of installation and management.

This might be a better conversation to open with the core Octave maintainers on the Octave Discourse forum at https://octave.discourse.group/.

In theory, BLAS is a generic interface, and you can build your application against BLAS generically, and then swap between implementations like OpenBLAS, Apple Accelerate, and Intel MKL at program launch time. But there's no convenient way to do that (especially with launching an app from /Applications), macOS's new Security stuff prevents doing it with LD_PRELOAD or the like, and Octave and/or some of its dependencies may link specifically against the BLAS implementation they're built against. Which means to make Accelerate available, that might mean producing an alternate Accelerate-using build. I'm already bummed about the fact that we have separate Intel and Apple Silicon architecture builds; I wouldn't want to introduce an Accelerate build in to the mix, especially because most Octave.app users won't even know what Accelerate is.

Plus, Octave.app is built on Homebrew, and the core Homebrew formula for octave only builds against openblas; no Accelerate support there. I've got limited resources and am having a hard enough time maintaining the Octave.app stuff we have now. Adding a custom formula variant that Octapp is the only project in the world using or supporting probably isn't something I'd want to take on.

IMHO, a more hopeful approach would be to get run-time BLAS-switching support built in to core Octave, including a GUI control for it. (Like, in the Preferences, there'd be an "Engine" tab or the like, with a dropdown where the user picks Default, OpenBLAS, Accelerate, or Intel MKL (or other BLAS implementations). You pick your BLAS there, restart Octave, and now you're running with that BLAS implementation. Sort of like how IDEs and editors like VS Code or PyCharm can be configured to switch between different Python or Java JDK installations in a single editor. Or maybe just a BLAS_VERSION environment variable like Matlab uses, as described in that blog post you linked.)

So, I can see why you'd want this feature. But I don't think it's something I can or will support for Octave.app any time soon. Parking this under the "The Future" milestone for future reconsideration.

Cheers,
Andrew

**Comment by tangjinchuan** [comment]
Dear Andrew,
Thank you very much for the very kind information. 
I remember a long time ago I tried to communicate with Octave developers via bug report about other BLAS lib support https://savannah.gnu.org/bugs/?63184 . From there, they would need users to take care of the BLAS lib if they like, but this will definitely take time and people to investigate. Both would be the things that Octave is lacking when compared to PyTorch. I believe PyTorch used Apple Accelerate based on Apple's announcement and the speed via M1/2/3/4 chip matrix coprocessor is indeed very fast. 
This also reminds me of the time I was helping to write the detailed steps for Homebrew installation tutorial @ https://wiki.octave.org/Octave_for_macOS for Apple Silicon. I was shocked to see nobody was helping for a quite long time on how to install it to Apple Silicon and how to make a correct launcher app without keep asking for permission at each directory. Another reason was your great Octave.app had no release for a quite long time, I have to find alternatives. I am very happy to see the new release is here.
So, if it is deemed complicated, I guess we just leave it there and waiting for someone to chip in because it is definitely good for the sake of humanity. This is the most important reason for I believe some people may use Octave to discover medicine and other stuffs to make humanity better. 
Apart from this, it is not a some other worry for me because I am involved in the development of gpuArray related NDArray ops based on OpenCL and Matt's project https://sourceforge.net/projects/octave-ocl/, which is also made available for Apple silicon https://sourceforge.net/projects/octave-ocl-extra/. Therefore, at least, the opensource community can have something on Apple silicon that others do not support or need CUDA devices.

Best wishes,
Jinchuan

**Comment by apjanke** [comment]
Yep. I think you have a good grasp on the situation here.

> how to make a correct launcher app without keep asking for permission at each directory

I'm afraid this is an unsolved problem, and not likely to be fixed unless we can [get code-signing working](https://github.com/octave-app/octave-app/issues/83), and probably not even then. That's just how newer versions of macOS want things to work, with their "sandboxing" and security stuff. :(

FWIW, there should only be a few special directories (like Documents, Downloads, etc.) that you need to approve, once for each installation of Octave.app. There's a related problem where when you switch between different versions of Octave.app or separately-installed Octaves, you need to re-approve for each installation. That's something we could maybe fix by modifying how the "app IDs" for each installation are defined, or something like that.

> Another reason was your great Octave.app had no release for a quite long time, I have to find alternatives. I am very happy to see the new release is here.

I appreciate it! Sorry for the long wait. I kind of took a year or two break from Octave.app work because of, well, Life and my day job, and how I was trying to stick on macOS 10.14 because of Aperture. But I'm back now, and hope to keep up better with new Octave releases. (I've got a [9.2 beta](https://github.com/octave-app/octave-app/releases/tag/v9.2.0_beta1) out already, and hope to do the real release of Octave.app 9.1 this weekend.)

> So, if it is deemed complicated, I guess we just leave it there and waiting for someone to chip in [...]

Yeah. It's complicated, and I don't think there's much I can do here in Octave.app without upstream support from core Octave. Especially if we want it to work well, instead of just barely work. So I'm going to close this ticket out and wait for core Octave to support this. (Or for me to learn something new about BLAS that presents a new easy approach, but I'm not holding my breath for that.) I am hopeful here, because those Accelerate speed gains are pretty impressive.

Thanks for the suggestion though, and let me know if you see anything change upstream or have an idea for a new approach!

**Comment by apjanke** [comment]
References for if we reconsider this:

* Homebrew ticket about using Accelerate with numpy
  * https://github.com/Homebrew/homebrew-core/issues/181251
* Octave Discourse discussions about Accelerate
  * [MacOS Accelerate.framework single-precision issue](https://octave.discourse.group/t/macos-accelerate-framework-single-precision-issue/6140)
  * ["Precision on macOS"](https://octave.discourse.group/t/precision-on-macos/6051)
