### ISSUE TITLE
Octave app 9.2.0 looking for Octave 9.1.0 libraries

### ISSUE THREAD

**Issue by denniscote** [octave-app/octave-app#282]
I have installed Octave 9.2.0 using homebrew. I am trying to use the signal and control packages but getting an error that seems to say Octave is looking for files in directory with "9.1.0" in the path. That directory does not exist, but there is a directory with "9.2.0" at that location in the path.

```
GNU Octave, version 9.2.0
Copyright (C) 1993-2024 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin22.6.0".

Home page:            https://octave.org
Support resources:    https://octave.org/support
Improve Octave:       https://octave.org/get-involved

For changes from previous versions, type 'news'.

>> pkg load signal
>> pkg load control
>> f=[100 1000 7000 8000];
>> w=2*pi*f;
>> h=[1 1 1 0];
>> fs=16000
fs = 16000
>> ts=1/fs;
>> sys=frd(h,w,ts)
error: /Users/dennis/.local/share/octave/api-v59/packages/control-4.0.0/x86_64-apple-darwin22.6.0-api-v59/__control_helper_functions__.oct: failed to load
Incompatible version or missing dependency?
dlopen(/Users/dennis/.local/share/octave/api-v59/packages/control-4.0.0/x86_64-apple-darwin22.6.0-api-v59/__control_helper_functions__.oct, 0x000A): Library not loaded: /usr/local/opt/octave/lib/octave/9.1.0/liboctinterp.12.dylib
  Referenced from: <989765C5-C272-3A4F-B5F8-711551CE9578> /Users/dennis/.local/share/octave/api-v59/packages/control-4.0.0/x86_64-apple-darwin22.6.0-api-v59/__control_helper_functions__.oct
  Reason: tried: '/usr/local/opt/octave/lib/octave/9.1.0/liboctinterp.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/octave/lib/octave/9.1.0/liboctinterp.12.dylib' (no such file), '/usr/local/opt/octave/lib/octave/9.1.0/liboctinterp.12.dylib' (no such file)
error: called from
    frd at line 129 column 31
>> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     control *|   4.0.0 | /Users/dennis/.local/share/octave/api-v59/packages/control-4.0.0
      signal *|   1.4.5 | /Users/dennis/.local/share/octave/api-v59/packages/signal-1.4.5
>>
```

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
>> system env
SHELL=/bin/zsh
TERM=xterm
TMPDIR=/var/folders/cl/stjvvn8d3r17cm9s3m1c5dr00000gn/T/
LC_NUMERIC=C
USER=dennis
http_proxy=
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.WJljd2b8zN/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x52
COLUMNS=155
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/octave/9.2.0/libexec/octave/9.2.0/site/exec/x86_64-apple-darwin22.6.0:/usr/local/Cellar/octave/9.2.0/libexec/octave/api-v59/site/exec/x86_64-apple-darwin22.6.0:/usr/local/Cellar/octave/9.2.0/libexec/octave/site/exec/x86_64-apple-darwin22.6.0:/usr/local/Cellar/octave/9.2.0/libexec/octave/9.2.0/exec/x86_64-apple-darwin22.6.0:/usr/local/Cellar/octave/9.2.0/bin
_=/usr/bin/env
__CFBundleIdentifier=com.apple.ScriptEditor.id.Octave
PWD=/
XPC_FLAGS=0x0
LINES=65
https_proxy=
HTTPS_PROXY=
XPC_SERVICE_NAME=0
HOME=/Users/dennis
SHLVL=2
HTTP_PROXY=
LOGNAME=dennis
DISPLAY=/private/tmp/com.apple.launchd.vHhTEN4liG/org.xquartz:0
LC_TIME=C
ans = 0
>>
```

**Comment by denniscote** [comment]
I forgot that the packages are not preinstalled in Octave on macOS like they are on Windows. I tried to install the latest version of the control package, but it failed with a "sh: gfortran: command not found" error. 

I had to modify the PATH in the Octave environment to add the path homebrew installation path to Octave's PATH as shown below.

```
setenv("PATH", ["/usr/local/bin:" getenv("PATH")])
```

After that the install of the latest control package completed with a single warning.

```
1 warning generated.
ld: warning: duplicate -bundle_loader option, '/usr/local/Cellar/octave/9.2.0/bin/octave-9.2.0' ignored
```

The control package function frd() now fails on macOS with the same error message as I get on Windows.

**Comment by apjanke** [comment]
Hi, @denniscote.

This ["octave-app" repo](https://github.com/octave-app/octave-app) is specifically for Octave.app, a "native Mac app" build & distribution of Octave, not GNU Octave in general. It doesn't look like you're running Octave.app here, and this is more of a general Octave issue. The support forum for regular Octave is over at https://octave.discourse.group/.

Anyway, it looks like your problem here is due to how oct-files are built and linked, maybe interacting with how Homebrew installs Octave. Oct-files are linked to some Octave DLLs like liboctinterp.dylib, and that linkage uses the full path to the DLL files' location under the Octave installation. Those oct-file-related DLLs are available under the common lib/ dir, but they're under a subdirectory, and that subdirectory tree also includes the Octave version to get to the actual DLLs. So a DLL won't be picked up by its base name and the regular $DYLD_LIBRARY_PATH, only through the paths referenced in linked files. (I think.)

```
[lib] $ pwd
/usr/local/lib
[lib] $ ls -l liboct*
ls: liboct*: No such file or directory
[lib] $ ls -l octave
lrwxr-xr-x  1 janke  admin  33 Jun 17 22:56 octave -> ../Cellar/octave/9.2.0/lib/octave
[lib] $ ls octave
octave
[lib] $ cd octave
[octave] $ pwd
/usr/local/lib/octave
[octave] $ ls
9.2.0
[octave] $ ls 9.2.0/
liboctave.11.dylib    liboctave.dylib       liboctgui.12.dylib    liboctgui.dylib       liboctinterp.12.dylib liboctinterp.dylib    oct
[octave] $
```

When you install an Octave package using `pkg`, it will compile any MEX-files or oct-files ("native extensions") in it. Those compiled oct-files will thus end up with linkage to the path for the current version of octave baked in to them.

Did you install the 'pkg' package using an older 9.1.0 version of Octave? Like, before a recent `brew upgrade`?
That would cause the "9.1.0" in that `/usr/local/opt/octave/lib/octave/9.1.0/liboctinterp.12.dylib` file it's looking for. I think that path comes from the linkage path built into the previously-compiled oct-files from the original package installation, not from something built in to the current version of Octave.

The upshot of this is that I think Octave Forge packages with native extensions (oct-files) can't be be shared between different versions of Octave (or different installation locations on disk), and must be re-compiled for each new Octave version. And the way to re-compile them I think is to uninstall and reinstall them. So if you previously installed `control` or other Octave packages with native extensions, uninstall and reinstall them, and they might start working.

In Octave.app, this is handled by having Octave.app customize the `pkg` installation location so that each version of Octave.app has its packages installed to a different version-specific location, and they're not shared between different versions of Octave.app. That's not the default behavior for Octave, at least time I checked.

Worth asking about over at https://octave.discourse.group/ to see what the Right Way to handle this in vanilla Octave is.

## Making gfortran available

> I had to modify the PATH in the Octave environment to add the homebrew installation path to Octave's PATH as shown below.
> 
> ```
> setenv("PATH", ["/usr/local/bin:" getenv("PATH")])
> ```

You need to have `/usr/local/bin` on your `$PATH` to use Homebrew tools (like gcc and gfortran) in general; that's not really Octave-specific. Octave relies on `$PATH` to find all those tools. It does seem unusual that `/usr/local/bin` wasn't there already, though. I think it's added by default in recent versions of macOS and not something a user has to do themself. (At least as far back as macOS 12, I think.) I'm guessing you're on an older version of macOS, then. If you want those Homebrew programs available everywhere (which I'm guessing you do), edit your `~/.profile` and/or `~/.zprofile` files to do `PATH="/usr/local/bin:$PATH"` to get it in all your shell sessions.

## Resolution

Closing this issue as not Octave.app-specific.

Good luck!
