### ISSUE TITLE
the tight dependency on a specific Java version is very limiting

### ISSUE THREAD

**Issue by FlorinAndrei** [octave-app/octave-app#37]
Is there a way to bundle Java with the Octave app, so that only Octave uses it?

Barring that, is there a way to install the Java version required by the Octave app in a particular directory, not system-wide, and have the Octave app somehow use that version?

I use Java for various things on my laptop, and it's a severe limitation to have the system-wide Java version restricted by a single app.

**Comment by apjanke** [comment]
> Is there a way to bundle Java with the Octave app, so that only Octave uses it?

Yes! We are currently working on an Octave.app 4.4.1 "u1" revision which will ship a bundled JDK as part of the Octave.app app bundle, so you will no longer have to worry about installing the correct-version JDK separately, and all users will get a Java-enabled Octave.app with no additional installation steps needed. (Tech details: we made a custom [openjdk Formula](https://github.com/octave-app/homebrew-octave-app/blob/master/Formula/openjdk.rb) instead of a Cask so it can be installed into the Octave.app build prefix and referenced from the `octave-octave-app` formulae.) The Octave.app 5.x.x releases will work this way, too.

I'm currently having health issues, so there's a bit of a delay in this release, but it should be out soon. (Like, within a few weeks.)

And, separately, we're working on getting dynamic Java JDK detection into upstream Octave, so all Octaves will soon be more flexible in which JDK installations they support; you'll no longer be stuck with the exact JDK version detected at compile time. Upstream bug: https://savannah.gnu.org/bugs/index.php?54219

**Comment by apjanke** [comment]
Beta2 for Octave.app 4.4.1-u1 is now available: https://github.com/octave-app/octave-app/releases/download/v4.4.1-u1-beta2/Octave-4.4.1-u1-beta2.dmg.

This build includes a bundled JDK, so it's independent of the system JDK and you don't have to worry about installing one yourself at all, and it should work regardless of what the JDK situation on your machine is. Could you download it and give it a try?

Sorry this took so long to get sorted.

**Comment by FlorinAndrei** [comment]
> Beta2 for Octave.app 4.4.1-u1 is now available

I only did a few tests, but seems fine AFAICT.

**Comment by apjanke** [comment]
Octave 4.4.1-u1 final is now released. Closing as fixed.

https://github.com/octave-app/octave-app/releases/tag/v4.4.1-u1
